### ISSUE TITLE
Front end/Admin side - Tracks || Cover image and Track music issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#79]
At Front end Tracks :  

Track cover images which I has added while adding track has not been seen at front end. Its broken
Also when Play music, it is not audible. In-short track binding is not proper at user side.

PFA

![Track cover image and audio is missing](https://user-images.githubusercontent.com/69690962/96489840-9b32fa80-125d-11eb-9207-fe3210ff3556.png)
![broken image and music is not audible in tracks](https://user-images.githubusercontent.com/69690962/96746038-67cea800-13e4-11eb-942a-cdfb4355c14a.png)

**Comment by smsan80** [comment]
Done

**Comment by sangeetajad** [comment]
Same issue is still existing...Cover Image is still not visible , Music file is not audible at User as well as admin side.
