### ISSUE TITLE
Frontend / Admin side Beats || Cover image and Beat music issue 

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/repo_edm#82]
Scenario :  

1) I have added new Beat, but in beat list page Added beat cover is missing and also when I unable play beat music at admin side.
2) Same issue is at user side as well. Cover image of beat is broken and when I play beat music , it is not audible.

PFA
![newly added beats not playing and image is missing](https://user-images.githubusercontent.com/69690962/96746425-c98f1200-13e4-11eb-8fa6-df064fe30b22.png)

![user side beats not playing and image is missing](https://user-images.githubusercontent.com/69690962/96746471-d57ad400-13e4-11eb-8061-b3c539d7047d.png)

**Comment by smsan80** [comment]
Done

**Comment by sangeetajad** [comment]
Same issue is still existing...Cover image is missing , Music is not audible at User side as well as Admin side.
